### ISSUE TITLE
Running build scripts blows up webpack

### ISSUE THREAD

**Issue by amite** [webpack/webpack-pwa#3]
I get this error:

```
webpack -p --env.appShell

Hash: 6f893c8bbaf1e6baf97b
Version: webpack 2.2.0
Time: 1008ms
                        Asset       Size  Chunks                    Chunk Names
               dashboard.html  202 bytes          [emitted]
      339b7b0e50cbacf7a044.js  297 bytes       0  [emitted]
      c7fb370947354ed1aeff.js    1.43 kB       2  [emitted]
      3d00f0c7841f11a322d3.js     352 kB       3  [emitted]  [big]
shell-8edb2e35229150fb950e.js    11.4 kB       4  [emitted]         shell
      db6fbc4d7edd8e2fda51.js    2.86 kB       1  [emitted]
                   login.html  202 bytes          [emitted]
                   admin.html  202 bytes          [emitted]
                        sw.js    7.83 kB          [emitted]
   appcache/manifest.appcache  262 bytes          [emitted]
       appcache/manifest.html   58 bytes          [emitted]
   [0] ./app/loading/page.js 217 bytes {4} [built]
   [1] ./app/app.js 2.19 kB {4} [built]
   [2] ./app/error/page.js 222 bytes {0} [built]
   [3] ./app async ^\.\/.*\/page$ 160 bytes {4} [built]
   [4] ./~/offline-plugin/runtime.js 1.29 kB {4} [built]
   [5] ./app/shell.js 128 bytes {4} [built]
   [6] ./app/admin/page.js 351 kB {3} [optional] [built]
   [7] ./app/dashboard/page.js 1.05 kB {1} [optional] [built]
   [8] ./app/login/page.js 415 bytes {2} [optional] [built]
   [9] ./app/utils/fetch.js 285 bytes {1} [built]
  [10] ./app/admin/page.html 190 bytes {3} [built]
  [11] ./app/dashboard/page.html 328 bytes {1} [built]
  [12] ./app/login/page.html 190 bytes {2} [built]

ERROR in db6fbc4d7edd8e2fda51.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [db6fbc4d7edd8e2fda51.js:27,65]

ERROR in c7fb370947354ed1aeff.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [c7fb370947354ed1aeff.js:25,69]

ERROR in 3d00f0c7841f11a322d3.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [3d00f0c7841f11a322d3.js:25,69]

ERROR in shell-8edb2e35229150fb950e.js from UglifyJs
SyntaxError: Unexpected character '`' [shell-8edb2e35229150fb950e.js:153,42]
Child __offline_serviceworker:
       [0] ./~/offline-plugin/empty-entry.js 0 bytes {0} [built]
       [1] ./~/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/offline-plugin/empty-entry.js 16.2 kB {0} [built]
Child html-webpack-plugin for "dashboard.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 540 bytes {0} [built]
Child html-webpack-plugin for "login.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 540 bytes {0} [built]
Child html-webpack-plugin for "admin.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 540 bytes {0} [built]

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/node" "/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/npm" "run" "build-shell"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-pwa@1.0.0 build-shell: `webpack -p --env.appShell`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webpack-pwa@1.0.0 build-shell script 'webpack -p --env.appShell'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-pwa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p --env.appShell
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-pwa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-pwa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amiterandole/Documents/current/webdev/webpack-pwa/npm-debug.log
```

Here is my error log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/node',
1 verbose cli   '/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle webpack-pwa@1.0.0~prebuild: webpack-pwa@1.0.0
6 silly lifecycle webpack-pwa@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle webpack-pwa@1.0.0~build: webpack-pwa@1.0.0
8 verbose lifecycle webpack-pwa@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-pwa@1.0.0~build: PATH: /Users/amiterandole/.nvm/versions/node/v7.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/amiterandole/Documents/current/webdev/webpack-pwa/node_modules/.bin:/Users/amiterandole/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Users/amiterandole/.nvm/versions/node/v7.0.0/bin:/usr/local/heroku/bin:/Users/amiterandole/.rbenv/shims:/Users/amiterandole/Sites/larasites/yiisite/framework:vendor/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin:/Users/amiterandole/.rbenv/shims:/usr/local/mysql/bin:/Users/amiterandole/.composer/vendor/bin:/usr/local/bin:/Users/amiterandole/Library/Haskell/bin:/Users/amiterandole/.local/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:./node_modules/.bin:/Users/amiterandole/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/Users/amiterandole/bin:/Users/amiterandole/Library/Haskell/bin:/Users/amiterandole/.local/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:./node_modules/.bin:/Users/amiterandole/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/Users/amiterandole/Sites/larasites/spark-installer:/Users/amiterandole/Library/Haskell/bin:/Users/amiterandole/.local/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:./node_modules/.bin:/Users/amiterandole/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/Users/amiterandole/bin:/Users/amiterandole/Library/Haskell/bin:/Users/amiterandole/.local/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:./node_modules/.bin:/Users/amiterandole/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin
10 verbose lifecycle webpack-pwa@1.0.0~build: CWD: /Users/amiterandole/Documents/current/webdev/webpack-pwa
11 silly lifecycle webpack-pwa@1.0.0~build: Args: [ '-c', 'webpack -p' ]
12 silly lifecycle webpack-pwa@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle webpack-pwa@1.0.0~build: Failed to exec build script
14 verbose stack Error: webpack-pwa@1.0.0 build: `webpack -p`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/Users/amiterandole/.nvm/versions/node/v7.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/amiterandole/.nvm/versions/node/v7.0.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid webpack-pwa@1.0.0
16 verbose cwd /Users/amiterandole/Documents/current/webdev/webpack-pwa
17 error Darwin 15.6.0
18 error argv "/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/node" "/Users/amiterandole/.nvm/versions/node/v7.0.0/bin/npm" "run" "build"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error webpack-pwa@1.0.0 build: `webpack -p`
22 error Exit status 2
23 error Failed at the webpack-pwa@1.0.0 build script 'webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack-pwa package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack-pwa
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack-pwa
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by sokra** [comment]
That's true, because the current uglifyjs version doesn't support ES2015.

Try to run `npm i mishoo/UglifyJS2#harmony` before running webpack

**Comment by amite** [comment]
That worked
